# Generated by Django 3.2.16 on 2022-12-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_simple_gallery', '0003_simplegalleryindex_order_images_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplegalleryindex',
            options={'verbose_name': 'Gallery index'},
        ),
    ]
